export const APIRoute = {
  Groups: {
    All: "/group",
    Info: `/group/:id`,
    Create: "/group",
    Update: `/group/:id`,
    Delete: `/group/:id`,
  },
  Bush: {
    All: "/bush",
    Info: `/bush/:id`,
    Create: "/bush",
    Update: `/bush/:id`,
    Delete: `/bush/:id`,
  },
  Users: {
    All: "/user",
    Info: `/user/:id`,
    Create: "/user",
    Update: `/user/:id`,
    Delete: `/user/:id`,
  },
  TaskPerformers: {
    All: "/task-performer",
    Info: `/task-performer/:id`,
    Create: "/task-performer",
    Update: `/task-performer/:id`,
    Delete: `/task-performer/:id`,
  },
  Manager: {
    All: "/manager",
    Info: `/manager/:id`,
    Create: "/manager",
    Update: `/manager/:id`,
    Delete: `/manager/:id`,
  },
  PetrolStation: {
    All: "/petrol-station",
    Info: `/petrol-station/:id`,
    Create: "/petrol-station",
    Update: `/petrol-station/:id`,
    Delete: `/petrol-station/:id`,
  },
  CheckAuth: "/check-auth",
} as const;
