export const APIRoute = {
  Category: {
    All: "/category",
    Info: `/category/:id`,
    Create: "/category",
    Update: `/category/:id`,
    Delete: `/category/:id`,
  },
  Priority: {
    All: "/priority",
    Info: `/priority/:id`,
    Create: "/priority",
    Update: `/priority/:id`,
    Delete: `/priority/:id`,
  },
  TagWord: {
    All: "/tag-word",
    Info: `/tag-word/:id`,
    Create: "/tag-word",
    Update: `/tag-word/:id`,
    Delete: `/tag-word/:id`,
  },
  Ticket: {
    All: "/ticket",
    Info: "/ticket/:id",
    Create: "/ticket",
    Update: "/ticket/:id",
    Delete: "/ticket/:id",
  },
  Status: {
    All: "/status",
    Info: "/status/:id",
    Create: "/status",
    Update: "/status/:id",
    Delete: "/status/:id",
  },
  StatusHistory: {
    All: "/status-history",
    Info: "/status-history/:id",
    Create: "/status-history",
    Update: "/status-history/:id",
    Delete: "/status-history/:id",
  },
  Comment: {
    All: "/comment",
    Info: "/comment/:id",
    Create: "/comment/",
    Update: "/comment/:id",
    Delete: "/comment/:id",
  },
  Attachment: {
    All: "/attachment",
    Info: "/attachment/:id",
    Create: "/attachment",
    Update: "/attachment/:id",
    Delete: "/attachment/:id",
  },
} as const;
