export const APIRoute = {
  Bush: {
    All: "/bushes",
    Info: `/bush/:id`,
    Create: "/bush/create",
    Update: `/bush/update/:id`,
    Delete: `/bush/delete/:id`,
  },
  Category: {
    All: "/categories",
    Info: `/category/:id`,
    Create: "/category/create",
    Update: `/category/update/:id`,
    Delete: `/category/delete/:id`,
  },
  Priority: {
    All: "/priorities",
    Info: `/priority/:id`,
    Create: "/priority/create",
    Update: `/priority/update/:id`,
    Delete: `/priority/delete/:id`,
  },
  TagWord: {
    All: "/tag-words",
    Info: `/tag-word/:id`,
    Create: "/tag-word/create",
    Update: `/tag-word/update/:id`,
    Delete: `/tag-word/delete/:id`,
  },
  Ticket: {
    All: "/tickets",
    Info: "/ticket/:id",
    Create: "/ticket/create",
    Update: "/ticket/update/:id",
    Delete: "/ticket/delete/:id",
  },
  Status: {
    All: "/statuses",
    Info: "/status/:id",
    Create: "/status/create",
    Update: "/status/update/:id",
    Delete: "/status/delete/:id",
  },
  StatusHistory: {
    All: "/status-histories",
    Info: "/status-history/:id",
    Create: "/status-history/create",
    Update: "/status-history/update/:id",
    Delete: "/status-history/delete/:id",
  },
  Comment: {
    All: "/comments",
    Info: "/comment/:id",
    Create: "/comment/create",
    Update: "/comment/update/:id",
    Delete: "/comment/delete/:id",
  },
  Attachment: {
    All: "/attachments",
    Info: "/attachment/:id",
    Create: "/attachment/create",
    Update: "/attachment/update/:id",
    Delete: "/attachment/delete/:id",
  },
} as const;
